/**
 * Data client for the frontend.
 *
 * WHY THIS FILE LOOKS DIFFERENT FROM A NORMAL API CLIENT:
 * This app is deployed 100% free on GitHub Pages (a static file host)
 * with no live backend server -- GitHub Actions can run the collector
 * on a schedule, but it cannot host a continuously-listening API for
 * the frontend to call, and Render/any paid host is explicitly out of
 * scope for this deployment. So instead of calling a FastAPI backend
 * over HTTP, this module fetches ONE static JSON snapshot
 * (public/data/jobs.json, regenerated by backend/scripts/export_jobs_json.py
 * after every collector run and redeployed automatically -- see
 * .github/workflows/) and reproduces the exact same search / filter /
 * sort / facet-counting logic that app/main.py's GET /jobs and GET
 * /jobs/facets endpoints implement, entirely in the browser.
 *
 * fetchJobs() and fetchFacets() below have the SAME parameters and
 * return the SAME shapes as before, so App.jsx and every other
 * component that calls them needed ZERO changes. The category/location
 * classification and relevance scoring itself is NOT reimplemented
 * here -- it's precomputed once in Python (the exact same,
 * unmodified app/categories.py / app/locations.py / app/relevance.py
 * functions) and shipped as extra fields on each job
 * (location_bucket, categories, relevance_score) inside jobs.json, so
 * this file only ever does simple, exact comparisons against those
 * precomputed values. The one deliberate simplification is search:
 * it matches substrings (including the same synonym groups the
 * backend uses, ported below) rather than calling a live endpoint --
 * behaviorally equivalent for this app's synonym-based "smart search".
 *
 * Known limitation of this static deployment (documented in README):
 * the Dashboard's "Collector Status" widget and the CSV/Excel/PDF
 * export buttons call a live backend that doesn't exist in this
 * deployment; they degrade gracefully (show nothing / no-op) rather
 * than breaking the rest of the app -- see README "Known limitations".
 */

// Vite sets this automatically from vite.config.js's `base` option --
// '/' locally, '/<repo-name>/' when built for GitHub Pages. Using it
// (instead of a hardcoded path) means this fetch works in both cases
// with no extra configuration.
const DATA_URL = `${import.meta.env.BASE_URL}data/jobs.json`

// --- Synonym groups, ported 1:1 from backend/app/synonyms.py --------
const SYNONYM_GROUPS = [
  ['sap pp', 'production planning', 'manufacturing consultant', 'pp consultant', 's/4 pp', 's4 pp'],
  ['sap qm', 'quality management', 'qm consultant', 'inspection lot'],
  ['hrbp', 'hr business partner', 'people partner', 'talent partner'],
  ['hr manager', 'human resources manager'],
  ['talent acquisition', 'recruiter', 'recruitment', 'talent sourcing'],
  ['learning & development', 'l&d', 'training & development'],
]
const SYNONYM_LOOKUP = {}
for (const group of SYNONYM_GROUPS) {
  for (const term of group) SYNONYM_LOOKUP[term] = group
}
function expandSearchTerms(query) {
  if (!query) return []
  const q = query.trim().toLowerCase()
  const group = SYNONYM_LOOKUP[q] || [q]
  return [...new Set([...group, q])].sort()
}

const SORT_OPTIONS = new Set(['newest', 'oldest', 'relevance', 'company', 'location'])

/** ISO timestamp string of when the current jobs.json snapshot was generated (or null). */
export async function getLastUpdated() {
  const payload = await loadData()
  return payload.generated_at || null
}

/** Forces the next data read to refetch jobs.json instead of reusing the cached promise (used by pull-to-refresh / the Refresh button). */
export function invalidateDataCache() {
  _dataPromise = null
}
let _dataPromise = null
function loadData() {
  if (!_dataPromise) {
    _dataPromise = fetch(DATA_URL, { cache: 'no-store' }).then((res) => {
      if (!res.ok) throw new Error(`Could not load job data (${res.status})`)
      return res.json()
    })
  }
  return _dataPromise
}

// --- Date/filter helpers, mirroring backend/app/main.py exactly ------
function parsePostedDate(value) {
  if (!value) return null
  const d = new Date(value)
  return Number.isNaN(d.getTime()) ? null : d
}

function ageCutoff(days) {
  const cutoff = new Date()
  cutoff.setUTCDate(cutoff.getUTCDate() - days)
  cutoff.setUTCMilliseconds(0)
  return cutoff
}

function isRecentEnough(job, cutoff) {
  const posted = parsePostedDate(job.posted_date)
  if (!posted) return true // null/missing/unparseable posted_date is never excluded
  return posted >= cutoff
}

function matchesSalary(job, salaryFilter) {
  if (!salaryFilter || salaryFilter === 'any') return true
  const hasSalary = Boolean(job.salary && job.salary.trim())
  if (salaryFilter === 'available') return hasSalary
  if (salaryFilter === 'not_listed') return !hasSalary
  return true
}

const POSTED_WITHIN_DAYS = { today: 1, 3: 3, 7: 7, 30: 30, 90: 90 }
function matchesPostedWithin(job, postedWithin) {
  if (!postedWithin) return true
  const days = POSTED_WITHIN_DAYS[postedWithin]
  if (days === undefined) return true
  const posted = parsePostedDate(job.posted_date)
  if (!posted) return false
  return posted >= ageCutoff(days)
}

function matchesSearch(job, search) {
  if (!search) return true
  const s = search.trim().toLowerCase()
  if (!s) return true
  const terms = expandSearchTerms(s)
  const haystack = [job.title, job.company, job.location, job.description]
    .filter(Boolean).join(' ').toLowerCase()
  return terms.some((t) => haystack.includes(t))
}

function matchesCategory(job, category) {
  if (!category || category === 'All Jobs') return true
  return (job.categories || []).includes(category)
}

function matchesLocationBucket(job, bucket) {
  if (!bucket || bucket === 'All') return true
  return job.location_bucket === bucket
}

function applyCommonFilters(jobs, { search, category, company, locationBucket, salary, postedWithin } = {}) {
  let result = jobs
  if (search) result = result.filter((j) => matchesSearch(j, search))
  if (category) result = result.filter((j) => matchesCategory(j, category))
  if (company) {
    const c = company.trim().toLowerCase()
    result = result.filter((j) => (j.company || '').trim().toLowerCase() === c)
  }
  if (locationBucket) result = result.filter((j) => matchesLocationBucket(j, locationBucket))
  if (salary) result = result.filter((j) => matchesSalary(j, salary))
  if (postedWithin) result = result.filter((j) => matchesPostedWithin(j, postedWithin))
  return result
}

async function loadBaseRows({ source } = {}) {
  const payload = await loadData()
  const cutoff = ageCutoff(payload.job_max_age_days ?? 90)
  let rows = payload.jobs
  if (source) rows = rows.filter((j) => j.source === source)
  rows = rows.filter((j) => isRecentEnough(j, cutoff))
  return rows
}

/**
 * Same parameters and same return shape ({ total, count, results }) as
 * the original GET /jobs call.
 */
export async function fetchJobs({
  search, source, locationBucket, category, company, salary, postedWithin, sort, page, pageSize,
} = {}) {
  const baseRows = await loadBaseRows({ source })
  const filtered = applyCommonFilters(baseRows, { search, category, company, locationBucket, salary, postedWithin })

  const sortKey = SORT_OPTIONS.has((sort || 'newest').toLowerCase()) ? (sort || 'newest').toLowerCase() : 'newest'
  const sorted = [...filtered]
  if (sortKey === 'oldest') {
    sorted.sort((a, b) => new Date(a.created_at || 0) - new Date(b.created_at || 0))
  } else if (sortKey === 'relevance') {
    sorted.sort((a, b) => (b.relevance_score ?? 0) - (a.relevance_score ?? 0))
  } else if (sortKey === 'company') {
    sorted.sort((a, b) => (a.company || '').toLowerCase().localeCompare((b.company || '').toLowerCase()))
  } else if (sortKey === 'location') {
    sorted.sort((a, b) => (a.location || '').toLowerCase().localeCompare((b.location || '').toLowerCase()))
  } else { // newest (default)
    sorted.sort((a, b) => new Date(b.created_at || 0) - new Date(a.created_at || 0))
  }

  const total = sorted.length
  let offset = 0
  let limit = 100
  if (page && pageSize) {
    offset = (page - 1) * pageSize
    limit = pageSize
  } else if (pageSize) {
    limit = pageSize
  }
  const results = sorted.slice(offset, offset + limit)
  return { total, count: results.length, results }
}

/**
 * Same parameters and same return shape ({ locations, categories,
 * companies, stats }) as the original GET /jobs/facets call, including
 * the same "every OTHER active filter applied, but not its own
 * dimension" faceted-search semantics.
 */
export async function fetchFacets({ search, source, locationBucket, category, company, salary, postedWithin } = {}) {
  const [baseRows, payload] = await Promise.all([loadBaseRows({ source }), loadData()])
  const allCategories = payload.all_categories || []
  const bucketOrder = payload.bucket_order || ['All', 'UAE', 'India', 'Germany', 'UK', 'Remote', 'Other']

  const withAllExcept = (exclude) => {
    const filters = { search, category, company, locationBucket, salary, postedWithin }
    filters[exclude] = undefined
    return applyCommonFilters(baseRows, filters)
  }

  const rowsForLocationCounts = withAllExcept('locationBucket')
  const locationCounts = Object.fromEntries(bucketOrder.map((b) => [b, 0]))
  for (const job of rowsForLocationCounts) {
    locationCounts.All = (locationCounts.All || 0) + 1
    const bucket = job.location_bucket || 'Other'
    locationCounts[bucket] = (locationCounts[bucket] || 0) + 1
  }
  const locations = bucketOrder.map((key) => ({ key, count: locationCounts[key] || 0 }))

  const rowsForCategoryCounts = withAllExcept('category')
  const categories = allCategories.map((cat) => ({
    key: cat,
    count: rowsForCategoryCounts.filter((j) => matchesCategory(j, cat)).length,
  }))

  const rowsForCompanyCounts = withAllExcept('company')
  const companyTally = {}
  for (const job of rowsForCompanyCounts) {
    const name = (job.company || '').trim()
    if (!name) continue
    companyTally[name] = (companyTally[name] || 0) + 1
  }
  const companies = Object.entries(companyTally)
    .sort((a, b) => b[1] - a[1] || a[0].toLowerCase().localeCompare(b[0].toLowerCase()))
    .slice(0, 100)
    .map(([name, count]) => ({ name, count }))

  const rowsForStats = applyCommonFilters(baseRows, { search, category, company, locationBucket, salary, postedWithin })
  const todayCutoff = ageCutoff(1)
  const isNewToday = (job) => {
    const posted = parsePostedDate(job.posted_date)
    return posted ? posted >= todayCutoff : false
  }
  const stats = {
    total: rowsForStats.length,
    new_today: rowsForStats.filter(isNewToday).length,
    remote: rowsForStats.filter((j) => j.location_bucket === 'Remote').length,
    uae: rowsForStats.filter((j) => j.location_bucket === 'UAE').length,
    india: rowsForStats.filter((j) => j.location_bucket === 'India').length,
    germany: rowsForStats.filter((j) => j.location_bucket === 'Germany').length,
    sap: rowsForStats.filter((j) => (j.categories || []).includes('SAP PP') || (j.categories || []).includes('SAP QM')).length,
  }

  return { locations, categories, companies, stats }
}

/**
 * Same shape as the original live GET /dashboard response
 * ({ total_jobs, jobs_today, latest_jobs }), derived from the same
 * static snapshot everything else in this file reads -- no live
 * backend involved.
 */
export async function fetchDashboard() {
  const baseRows = await loadBaseRows({})
  const todayCutoff = ageCutoff(1)
  const jobsToday = baseRows.filter((j) => {
    const created = parsePostedDate(j.created_at)
    return created ? created >= todayCutoff : false
  }).length

  const latestJobs = [...baseRows]
    .sort((a, b) => new Date(b.created_at || 0) - new Date(a.created_at || 0))
    .slice(0, 10)

  return {
    total_jobs: baseRows.length,
    jobs_today: jobsToday,
    latest_jobs: latestJobs,
  }
}
